### ISSUE TITLE
Add flag to run in series

### ISSUE THREAD

**Issue by RyanZim** [egoist/testen#13]
Libraries and CLIs that write to the filesystem during testing can fail when using testen because testen runs the different node versions in parallel on the same machine.

For example, https://github.com/rocktemplates/rock tests pass when running `npm test`, but fails when running `testen`. Running `testen -n 6 && testen -n 4` passes.

Could you add a CLI flag to run the different versions in series?

**Comment by egoist** [comment]
Thanks for reporting this, yep, I think it should be able to run tests in serial too.

**Comment by RyanZim** [comment]
@egoist I would be willing to work on this, but I'm not familiar with `co`. https://github.com/egoist/testen/blob/1.0/testen#L245-L247 is the relevant code.

**Comment by egoist** [comment]
I added this feature in `v2.0.0`, just try `--sequence` or `-s`

**Comment by RyanZim** [comment]
Thanks, works great!
