### ISSUE TITLE
testen should install missing node versions instead of failing

### ISSUE THREAD

**Issue by balupton** [egoist/testen#15]
it would be nice if testen installed missing node versions

**Comment by goldingdamien** [comment]
The page below seems to show how to do it:
https://stackoverflow.com/questions/49436894/set-node-version-with-nvm-or-install-if-not-available?rq=1

**Comment by balupton** [comment]
Alright. I've accomplished it over at [bevry/testen](https://github.com/bevry/testen). And is live on the `@bevry/testen` npm package with version 3.0.0.

The fork is a significant rewrite, hence why it is a fork instead of a PR.

@egoist if you would like to co-maintain the new package with me, that would be great. The only caveat though is that it would have to remain on the `bevry` github org, due to the automated release cycle that is now adopted. (the documentation publish and npm release occur via continuous integration). I'd add you as a team member on the @bevry org, and you'd have write access to the repo. Any git tag will trigger a new release, and git tags can be verified and created via `npm run our:release:prepare` then `npm our:release` as detailed in the `CONTRIBUTING.md` document. [Happy to discuss this with you!](https://balupton.com/meet)
