### ISSUE TITLE
Read travis.yml

### ISSUE THREAD

**Issue by dthree** [egoist/testen#5]
Great project, love it!

As a vast majority of Node developers use travis, can you look for a `.travis.yml` and if one exists, use the versions as declared in there? 

If you want people to use this, IMHO the most important thing is to make it as simple as possible, almost transparent. So ideally `npm test` can have a one-word supplant of `testen`, and it will behave locally like travis does remotely.

**Comment by egoist** [comment]
> look for a .travis.yml and if one exists

Yes, I was planning to do this. But do you think we should enable this by default or pass an option like `--yml` to make it? The option may be useful if we want to check `circle.yml` too.

> So ideally npm test can have a one-word supplant of testen

What do you mean by one-word supplant of `testen`? Currently running `testen` will run `npm test` by default. Just like what travis does.

**Comment by dthree** [comment]
I absolutely think it should be by default, unless explicitly overwritten by `-n` or a `testen` object in the `package.json`.

>  The option may be useful if we want to check circle.yml too.

Check for both. If travis is present, use it. If circle, use that.

Believe me, for casual testing while developing, a majority of users aren't going to want to specify _another_ config or think about remembering option names. Just `testen` and nothing else is brilliant.

For the small percentage who want to be explicit, that when you have options and an entry in `package.json`.

My two cents.

**Comment by egoist** [comment]
Nice advice 👍

**Comment by dthree** [comment]
:+1:

**Comment by dthree** [comment]
Awesome! :star2:
